"""Encrypt and authenticate keys, filenames, file chunks, and ACL records.

Canonical associated data binds ciphertext to its user, file, version, or chunk
position. Domain labels and encodings are persistent format contracts. Binding
detects context changes; it does not establish freshness of an authentic old row.
See docs/security-model.md for the key hierarchy and stored-state integrity model.
"""

import hashlib
import hmac
import json
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.exceptions import InvalidTag

# AES-GCM standard nonce length. 96 bits is the size GCM is defined and optimised for.
NONCE_LEN = 12
KEY_LEN = 32  # AES-256
TAG_LEN = 16  # GCM authentication tag, appended to the ciphertext by `cryptography`


# Keys are generated by the service. This format does not provide a separate
# key-commitment mechanism for adversarially supplied keys.
class KeyBindingError(Exception):
    """Raised when an AAD-bound unwrap fails: wrong user, wrong file, wrong version,
    or tampered ciphertext. Treat as an attack indicator, not a routine error."""


# --------------------------------------------------------------------------------------
# Canonical AAD encoding
# --------------------------------------------------------------------------------------


def _aad(**fields) -> bytes:
    """Build the associated data as canonical JSON (sorted keys, no whitespace).

    Why not just concatenate the fields: concatenation is ambiguous. With plain joining,
    user_id="ab", file_id="c" and user_id="a", file_id="bc" produce the same byte string,
    so a wrapped key could be replayed across a different (user, file) pair. Canonical JSON
    keeps the field boundaries explicit, so distinct contexts always produce distinct AAD.
    (Same class of bug as password+pepper concatenation — see g8auth.pre_hash.)
    """
    return json.dumps(fields, separators=(",", ":"), sort_keys=True).encode("utf-8")


def _seal(key: bytes, plaintext: bytes, aad: bytes):
    """AES-256-GCM encrypt. Returns (nonce, ciphertext_with_tag)."""
    if len(key) != KEY_LEN:
        raise ValueError("key must be %d bytes" % KEY_LEN)
    nonce = os.urandom(NONCE_LEN)
    ct = AESGCM(key).encrypt(nonce, plaintext, aad)
    return nonce, ct


def _open(key: bytes, nonce: bytes, ct: bytes, aad: bytes) -> bytes:
    """AES-256-GCM decrypt. Raises KeyBindingError if the tag or the AAD does not match.

    the key length is checked here as well as in _seal. Without it a wrong-length key
    raised ValueError from the library rather than KeyBindingError, so it escaped the
    endpoints as an unhandled 500 instead of being handled as the attack indicator it is.
    Errors on this path should all look the same to a caller and all be catchable in one
    place.
    """
    if len(key) != KEY_LEN:
        raise KeyBindingError("key must be %d bytes, got %d" % (KEY_LEN, len(key)))
    try:
        return AESGCM(key).decrypt(nonce, ct, aad)
    except InvalidTag:
        raise KeyBindingError(
            "AEAD tag check failed - ciphertext was tampered with, or the AAD context "
            "(user_id / file_id / version) does not match the one used at wrap time"
        )


# --------------------------------------------------------------------------------------
# Layer 1:  User_KEK, wrapped by the Service_Root-derived user_kek_wrap sub-key
# --------------------------------------------------------------------------------------


def new_user_kek() -> bytes:
    """Generate a fresh per-user KEK (AES-256)."""
    return os.urandom(KEY_LEN)


def wrap_user_kek(user_kek: bytes, user_id: str, version: int, wrap_key: bytes):
    """Wrap a user KEK with its identity and version authenticated.

    Args:
        user_kek: Plain user key to protect.
        user_id: Account identifier included in associated data.
        version: Key version included in associated data.
        wrap_key: Service-derived 32-byte wrapping key.

    Returns:
        A (nonce, ciphertext_with_tag) pair for persistence.
    """
    aad = _aad(t="user_kek", uid=user_id, v=int(version))
    return _seal(wrap_key, user_kek, aad)


def unwrap_user_kek(
    nonce: bytes, ct: bytes, user_id: str, version: int, wrap_key: bytes
) -> bytes:
    """Recover a user KEK only in its original authenticated context.

    Args:
        nonce: Stored 96-bit AES-GCM nonce.
        ct: Wrapped user-key ciphertext including its authentication tag.
        user_id: Expected account identifier, authenticated as associated data.
        version: Expected user-key version.
        wrap_key: Service-derived 32-byte wrapping key.

    Returns:
        Plain user-key bytes.

    Raises:
        KeyBindingError: The key length, tag, or identity/version binding fails.
    """
    aad = _aad(t="user_kek", uid=user_id, v=int(version))
    return _open(wrap_key, nonce, ct, aad)


# --------------------------------------------------------------------------------------
# Layer 2:  File_DEK, wrapped by a User_KEK  (one wrapped copy per authorised user)
# --------------------------------------------------------------------------------------


def new_file_dek() -> bytes:
    """Generate a fresh per-file DEK (AES-256)."""
    return os.urandom(KEY_LEN)


def wrap_file_dek(
    file_dek: bytes, user_id: str, file_id: str, version: int, user_kek: bytes
):
    """Wrap a file key for one user's authenticated access record.

    Args:
        file_dek: Existing file key; sharing does not generate a replacement.
        user_id: Recipient account identifier.
        file_id: File identifier.
        version: File-key version.
        user_kek: Recipient's 32-byte wrapping key.

    Returns:
        A (nonce, ciphertext_with_tag) pair bound to user, file, and version.
    """
    aad = _aad(t="file_dek", uid=user_id, fid=file_id, v=int(version))
    return _seal(user_kek, file_dek, aad)


def unwrap_file_dek(
    nonce: bytes, ct: bytes, user_id: str, file_id: str, version: int, user_kek: bytes
) -> bytes:
    """Recover a file key using the expected user, file, and version.

    Args:
        nonce: Stored 96-bit AES-GCM nonce.
        ct: Wrapped file-key ciphertext including its authentication tag.
        user_id: Expected recipient account identifier.
        file_id: Expected file identifier.
        version: Expected wrapped-key version.
        user_kek: Recipient's 32-byte user key.

    Returns:
        Plain file-key bytes.

    Raises:
        KeyBindingError: Authentication or context binding fails.
    """
    aad = _aad(t="file_dek", uid=user_id, fid=file_id, v=int(version))
    return _open(user_kek, nonce, ct, aad)


# --------------------------------------------------------------------------------------
# Filenames — encrypted, because the DB operator is a named adversary
# --------------------------------------------------------------------------------------


def encrypt_filename(name: str, file_id: str, version: int, file_dek: bytes):
    """Encrypt a UTF-8 filename with file/version context binding.

    Args:
        name: Plain filename to encode as UTF-8.
        file_id: File identifier authenticated as associated data.
        version: File version authenticated as associated data.
        file_dek: 32-byte file encryption key.

    Returns:
        A (nonce, ciphertext_with_tag) pair for the metadata record.
    """
    aad = _aad(t="filename", fid=file_id, v=int(version))
    return _seal(file_dek, name.encode("utf-8"), aad)


def decrypt_filename(
    nonce: bytes, ct: bytes, file_id: str, version: int, file_dek: bytes
) -> str:
    """Authenticate and decode a stored filename.

    Args:
        nonce: Stored 96-bit AES-GCM nonce.
        ct: Encrypted filename including its authentication tag.
        file_id: Expected file identifier.
        version: Expected file version.
        file_dek: 32-byte file decryption key.

    Returns:
        The UTF-8 filename.

    Raises:
        KeyBindingError: Ciphertext or file/version binding fails.
        UnicodeDecodeError: Authenticated bytes are not valid UTF-8.
    """
    aad = _aad(t="filename", fid=file_id, v=int(version))
    return _open(file_dek, nonce, ct, aad).decode("utf-8")


# Chunk AAD binds file ID, version, position, and total count. This detects
# reordering and truncation when the expected context is trusted. Files are
# write-once; changing their length requires a new authenticated representation.
CHUNK_SIZE = 4 * 1024 * 1024  # 4 MiB of plaintext per chunk (D11 decision 1)


def _chunk_aad(file_id: str, version: int, index: int, total: int) -> bytes:
    return _aad(t="chunk", fid=file_id, v=int(version), i=int(index), n=int(total))


def encrypt_chunk(
    plaintext: bytes,
    file_id: str,
    version: int,
    index: int,
    total: int,
    file_dek: bytes,
):
    """Seal a chunk with a fresh nonce and its position authenticated.

    Args:
        plaintext: Chunk bytes, possibly empty for a zero-byte file.
        file_id: File identifier.
        version: File version.
        index: Zero-based chunk position.
        total: Expected number of chunks in the complete file.
        file_dek: File encryption key.

    Returns:
        A (nonce, ciphertext_with_tag) pair. Nonces must never be reused under
        the same key; the API's upload cap bounds chunks per generated file key.
    """
    return _seal(file_dek, plaintext, _chunk_aad(file_id, version, index, total))


def decrypt_chunk(
    nonce: bytes,
    ct: bytes,
    file_id: str,
    version: int,
    index: int,
    total: int,
    file_dek: bytes,
) -> bytes:
    """Open a chunk in its expected file, version, and position.

    Args:
        nonce: Stored 96-bit AES-GCM nonce.
        ct: Chunk ciphertext including its authentication tag.
        file_id: Expected file identifier.
        version: Expected file version.
        index: Expected zero-based position in the file.
        total: Expected total chunk count.
        file_dek: 32-byte file decryption key.

    Returns:
        Authenticated plaintext bytes.

    Raises:
        KeyBindingError: The tag or any associated-data field does not match.
    """
    return _open(file_dek, nonce, ct, _chunk_aad(file_id, version, index, total))


def chunk_count(size_bytes: int, chunk_size: int = None) -> int:
    """Calculate the number of authenticated chunks for a file.

    Args:
        size_bytes: Plaintext size. Non-positive values produce one chunk.
        chunk_size: Optional size override; false values use CHUNK_SIZE.

    Returns:
        At least one chunk, so an empty file still has an authentication tag.
    """
    cs = chunk_size or CHUNK_SIZE
    if size_bytes <= 0:
        return 1
    return (size_bytes + cs - 1) // cs


# The wrapped file key grants access. ACL MACs separately authenticate permission
# metadata; read and write currently have the same effective capability.
def acl_mac(
    file_id: str, user_id: str, permission: str, version: int, mac_key: bytes
) -> bytes:
    """HMAC-SHA256 over the canonical encoding of one access-control row.

    Args:
        file_id: File identifier whose access is recorded.
        user_id: Recipient account identifier.
        permission: Permission label included in the authenticated record.
        version: Record version to authenticate.
        mac_key: Service-derived ACL HMAC key.
    """
    body = _aad(t="acl", fid=file_id, uid=user_id, p=permission, v=int(version))
    return hmac.new(mac_key, body, hashlib.sha256).digest()


def verify_acl(
    mac: bytes,
    file_id: str,
    user_id: str,
    permission: str,
    version: int,
    mac_key: bytes,
) -> bool:
    """Constant-time verification of an ACL row's MAC.

    Args:
        mac: Stored HMAC bytes to verify.
        file_id: File identifier from the ACL record.
        user_id: Recipient identifier from the ACL record.
        permission: Permission label from the ACL record.
        version: Version from the ACL record.
        mac_key: Service-derived ACL HMAC key.
    """
    expected = acl_mac(file_id, user_id, permission, version, mac_key)
    return hmac.compare_digest(expected, bytes(mac))


# --------------------------------------------------------------------------------------
# Demonstration — the adversarial cases are the point
# --------------------------------------------------------------------------------------

if __name__ == "__main__":
    import hashlib
    import g8auth

    def check(label, fn, expect_reject=True):
        try:
            fn()
            ok = not expect_reject
            outcome = "unwrapped"
        except KeyBindingError:
            ok = expect_reject
            outcome = "REJECTED"
        print("  [%s] %-52s -> %s" % ("PASS" if ok else "FAIL", label, outcome))
        return ok

    print("=" * 74)
    print("g8keys demonstration - key hierarchy with AAD binding")
    print("=" * 74)

    keys = g8auth.load_keys()
    wrap_key = keys["user_kek_wrap"]
    print(
        "[keys] user_kek_wrap fingerprint:",
        hashlib.sha256(wrap_key).hexdigest()[:16],
        "...",
    )

    alice, bob = "alice-0001", "bob-0002"
    f1, f2 = "file-aaaa", "file-bbbb"

    # --- build the hierarchy -----------------------------------------------------------
    a_kek, b_kek = new_user_kek(), new_user_kek()
    a_n, a_ct = wrap_user_kek(a_kek, alice, 1, wrap_key)
    b_n, b_ct = wrap_user_kek(b_kek, bob, 1, wrap_key)

    dek = new_file_dek()
    a_dn, a_dct = wrap_file_dek(dek, alice, f1, 1, a_kek)

    print("\n-- happy path --")
    check(
        "Alice unwraps her own User_KEK",
        lambda: unwrap_user_kek(a_n, a_ct, alice, 1, wrap_key),
        expect_reject=False,
    )
    check(
        "Alice unwraps her File_DEK for file-aaaa",
        lambda: unwrap_file_dek(a_dn, a_dct, alice, f1, 1, a_kek),
        expect_reject=False,
    )

    got = unwrap_file_dek(a_dn, a_dct, alice, f1, 1, a_kek)
    print("  [%s] File_DEK round-trips byte-exact" % ("PASS" if got == dek else "FAIL"))

    # --- sharing: same DEK, second wrap, file untouched --------------------------------
    b_dn, b_dct = wrap_file_dek(dek, bob, f1, 1, b_kek)
    shared = unwrap_file_dek(b_dn, b_dct, bob, f1, 1, b_kek)
    print(
        "  [%s] sharing: Bob's wrapped copy yields the SAME File_DEK (file never re-encrypted)"
        % ("PASS" if shared == dek else "FAIL")
    )

    # --- the adversarial cases: attacker has FULL write access to the DB ---------------
    print("\n-- attacker with full database write access (D1 threat model) --")

    check(
        "T6a Bob replays Alice's wrapped-DEK row onto himself",
        lambda: unwrap_file_dek(a_dn, a_dct, bob, f1, 1, b_kek),
    )

    check(
        "T6b Alice's row relabelled as a different file_id",
        lambda: unwrap_file_dek(a_dn, a_dct, alice, f2, 1, a_kek),
    )

    check(
        "T6c stale version replayed after rotation",
        lambda: unwrap_file_dek(a_dn, a_dct, alice, f1, 2, a_kek),
    )

    check(
        "T6d Alice's User_KEK row copied onto Bob's account",
        lambda: unwrap_user_kek(a_n, a_ct, bob, 1, wrap_key),
    )

    tampered = bytearray(a_dct)
    tampered[0] ^= 0x01
    check(
        "T5  single bit flipped in the wrapped DEK",
        lambda: unwrap_file_dek(a_dn, bytes(tampered), alice, f1, 1, a_kek),
    )

    check(
        "T6e wrapped DEK opened with the wrong User_KEK",
        lambda: unwrap_file_dek(a_dn, a_dct, alice, f1, 1, b_kek),
    )

    # --- filenames ---------------------------------------------------------------------
    print("\n-- encrypted filenames --")
    fn_n, fn_ct = encrypt_filename("salary_review_2026.pdf", f1, 1, dek)
    print("  stored bytes (what the DB operator sees):", fn_ct[:24].hex(), "...")
    back = decrypt_filename(fn_n, fn_ct, f1, 1, dek)
    print(
        "  [%s] filename round-trips: %r"
        % ("PASS" if back == "salary_review_2026.pdf" else "FAIL", back)
    )
    check(
        "     filename row relabelled to another file_id",
        lambda: decrypt_filename(fn_n, fn_ct, f2, 1, dek),
    )

    # --- chunks: the arrangement attacks ------------------------------------------
    print("\n-- file chunks: an attacker who can rearrange storage (D11) --")

    parts = [b"AAAA-chunk-zero", b"BBBB-chunk-one", b"CCCC-chunk-two"]
    total = len(parts)
    sealed = [encrypt_chunk(p, f1, 1, i, total, dek) for i, p in enumerate(parts)]

    rebuilt = b"".join(
        decrypt_chunk(n, c, f1, 1, i, total, dek) for i, (n, c) in enumerate(sealed)
    )
    print(
        "  [%s] all chunks round-trip in order, byte-exact"
        % ("PASS" if rebuilt == b"".join(parts) else "FAIL")
    )

    check(
        "chunk 0 replayed at position 1 (REORDER)",
        lambda: decrypt_chunk(sealed[0][0], sealed[0][1], f1, 1, 1, total, dek),
    )

    check(
        "chunk 2 duplicated over position 1 (DUPLICATE)",
        lambda: decrypt_chunk(sealed[2][0], sealed[2][1], f1, 1, 1, total, dek),
    )

    check(
        "last chunk dropped, file re-read as 2 chunks (TRUNCATE)",
        lambda: decrypt_chunk(sealed[0][0], sealed[0][1], f1, 1, 0, total - 1, dek),
    )

    check(
        "chunk spliced in from a different file (SPLICE)",
        lambda: decrypt_chunk(sealed[0][0], sealed[0][1], f2, 1, 0, total, dek),
    )

    bad = bytearray(sealed[1][1])
    bad[3] ^= 0x01
    check(
        "single bit flipped inside a chunk (TAMPER)",
        lambda: decrypt_chunk(sealed[1][0], bytes(bad), f1, 1, 1, total, dek),
    )

    check(
        "chunk opened with the wrong File_DEK",
        lambda: decrypt_chunk(
            sealed[1][0], sealed[1][1], f1, 1, 1, total, new_file_dek()
        ),
    )

    print("\n  note: every one of those chunks is individually authentic. Only the AAD")
    print("        binding of position, file and total length makes the ARRANGEMENT")
    print("        authentic too.")

    print("\nDEMONSTRATION COMPLETE")
    print(
        "Every row in the untrusted DB is bound to its (user, file, version) context."
    )
    print("Changing a row's authenticated context makes unwrapping fail.")
